### ISSUE TITLE
Consistency of param names in table()

### ISSUE THREAD

**Issue by kamenov** [PhilterPaper/PDF-Table#13]
header_props->{bg_color} to become header_props->{background_color}
check for other such cases

**Comment by PhilterPaper** [comment]
I'm not sure there's a point to this. The original names have been around long enough that they've probably been widely used. Changing them would break a lot of code. Adding _aliases_ rather than _renaming_ parameter names could retain compatibility, but again, what's the point?

**Comment by PhilterPaper** [comment]
Comment from Desislav:

> I agree with you and I think if you combine it with #5 and #7, then this can be isolated and would not bloat the code.

**Comment by PhilterPaper** [comment]
Update for release 1.000: many parameters are now available in shorter, more consistent names, such as **bg_color** instead of **background_color**. The old names are marked as _deprecated_ and will eventually (at least two years from release) go away, so you have plenty of time to update your code.
