### ISSUE TITLE
Option to disable carp warnings

### ISSUE THREAD

**Issue by matthewlenz** [PhilterPaper/PDF-Table#30]
Would be nice to disable the warnings.  The one below is especially difficult to avoid when you are working with highly variable input data.

```
    # I think this is the optimal variant when good view can be guaranateed
    if($avail_width < $min_width)
    {
        carp "!!! Warning !!!\n Calculated Mininal width($min_width) > Table width($avail_width).\n",
            ' Expanding table width to:',int($min_width)+1,' but this could lead to unexpected results.',"\n",
            ' Possible solutions:',"\n",
            '  0)Increase table width.',"\n",
            '  1)Decrease font size.',"\n",
            '  2)Choose a more narrow font.',"\n",
            '  3)Decrease "max_word_length" parameter.',"\n",
            '  4)Rotate page to landscape(if it is portrait).',"\n",
            '  5)Use larger paper size.',"\n",
            '!!! --------- !!!',"\n";
        $avail_width = int( $min_width) + 1;

    }

```

**Comment by kamenov** [comment]
Agreed!

Would you please propose a patch and I will merge+release it asap.

Thanks!

**Comment by PhilterPaper** [comment]
Before starting on this, rather than doing it piecemeal, let's get a list of carp "warnings" of this type (that perhaps should be a Note or Info, instead of Warning). Then, add a flag option to new() to suppress this level of warning:

`new( msglevel => 'warn' )`   sets $msglevel to 1

`if ($msglevel >= 1) { carp ... }`

**Comment by PhilterPaper** [comment]
Thinking about it some more, this is a _forced_ widening of the table due to its content minimum width being too wide. It might be counterproductive to **silently** widen the table, especially if it exceeds the available page space! Perhaps a silent widening could be tolerated if the whole table still fits on the page, or something could be done to narrow the columns (as suggested in 1, 2, and 3). If you're going to lose content (page overflow) or destroy the page structure, PDF::Table should not be quiet about it!

If you're still around, @matthewlenz (your avatar looks like you're at death's door!), perhaps you could give some examples of "highly variable" input data and how it might be dealt with. If you have normally small numbers and occasional big ones, those would be hard to split cleanly. Do you normally have short words and occasional long words?

An additional option that comes to mind would be to destroy the grid structure of the table, and allow columns to enlarge shift left or right to consume unused space in neighboring columns. That could be confusing to (human) readers, though.

**Comment by PhilterPaper** [comment]
This _particular_ error/warning message could probably do with some trimming (shortening), and leave the list of remedies in the POD instead. That alone might make it more tolerable for users.

**Comment by PhilterPaper** [comment]
Update for release 1.000: this message has been greatly shortened, with most of the remedial content moved to the POD. I haven't decided yet about making a control whether or not to see the message at all. Maybe in a later release? I'm reluctant to entirely remove such useful information.

**Comment by PhilterPaper** [comment]
Let's let users play with release 1.000, and see if the remaining Carp warnings etc. are still annoying. A warning or error message is supposed to mean that something is seriously wrong, so I am reluctant to give a means of hiding them.
