### ISSUE TITLE
Warns when a table spills over on to the next page?

### ISSUE THREAD

**Issue by djzort** [PhilterPaper/PDF-Table#42]
This example produces a warning when the table spills over on to the next page.
The warning is

> !!! Warning: !!! Incorrect Table Geometry! Setting bottom margin to end of sheet!
>  at pdftable.pl line 19.

Code is as follows

```
#!/usr/bin/env perl
# vim: softtabstop=4 tabstop=4 shiftwidth=4 ft=perl expandtab smarttab

use warnings;
use strict;

use PDF::API2;
use PDF::Table;

my $pdftable = PDF::Table->new();

my $pdf = PDF::API2->new();
$pdf->mediabox('A4');

my $page = $pdf->page();

$pdftable->table(
    $pdf, $page,
    [ map { [ 1..10 ] } (1..10) ],
    x => 50,
    w => 495,
    start_y => 200,
    start_h => 300,
    next_y => 750,
    next_h => 500,
    padding => 5,
    padding_right => 10,
);

$pdf->saveas( '/tmp/table.pdf' );

```

It seems that spilling over is the desired outcome, so the warning is probably the wrong behavior? Perhaps the spillover should be controllable some how?

**Comment by PhilterPaper** [comment]
To be honest, I'm not sure what the purpose of `start_h` and `next_h` are! A quick look over the code suggests that we could do without them, and set the (max) height to the available space. No more annoying warnings. Perhaps it should be a _maximum height_  with no warnings, rather than a _fixed height_ (which can be ignored anyway)? I'll have to look at it again later this year when I get some more time to work on it.

If someone knows if these settings had a different intended usage, that perhaps hadn't been implemented yet, please speak up!

**Comment by PhilterPaper** [comment]
While working on this, see also #11 to override `next_h` and `next_y` default values.

**Comment by djzort** [comment]
Thanks @PhilterPaper

**Comment by PhilterPaper** [comment]
Update for release 1.000: for routine spills (table continuations to a new page), there will be no message. Possibly an _optional_ message could be added (for informational use), but that's not in the current plans.

**Comment by djzort** [comment]
I woudl recommend optionally throwing an exception (ie die) so that the code calling knows its happened and can act on it. Warnings just let lost in logs and if you want to act on them you have to do lots of nasty stuff

**Comment by PhilterPaper** [comment]
So you want to be able to kill the whole thing if the table spans more than one page? That seems kind of extreme to me, but it's not hard to do. One of the items on my enhancements list is the ability to control how and if a table is split over pages -- this might go in that category. Maybe a query for how long the table is expected to be would be useful, and the user could then choose to skip to the top of the next page to start the table? There currently isn't any place in PDF::Table to calculate the entire length (height) before outputting any ink, but a dummy run flag (don't actually write anything) might be feasible.

**Comment by djzort** [comment]
you can catch a die() then then decide what to do.

*shrug* its hard to catch a warn. 

maybe a callback instead?

**Comment by PhilterPaper** [comment]
Ah, I had never seen Perl code to catch a `die()`. I'm not too familiar with exception handling ("try" and "catch" style?) but I'll have to play with this some time. 

The problem at hand is that you presumably don't want to put down any ink before discovering that you will spill to the next page. Simply die()ing when you get to the end of the page and find you need to spill to a new page doesn't sound very useful if you've already written several rows. If the objective is (for a table that will fit on one page) to skip to the next page top to start the table, you'd have to erase the ink already output (it's probably still in the `$pdf` hash at this point, so that might be possible). Still, it might be cleaner to do a dummy (nonprinting) run first, revealing the break point for each row and the overall table length, so you can decide whether to start the table at the current page position, or skip to page top first, and even set 'start_h' and 'next_h' to control where the breaks are.

Would something like that meet your requirements? I don't think it could get out in 1.000 (coming soon), but it could go in the hopper for a later release.

**Comment by djzort** [comment]
try/catch is just fancier (and slower) version of eval

after reading your thoughts i agree that an exception is the wrong approach. 

Laying it out to look for problems is an interesting two or more step approach. For my usage probably a callback would be best. So if the table rolls over some anonymous subroutine that is provided by the caller is run. Then some actions can be taken ?

**Comment by PhilterPaper** [comment]
You still have the problem that ink has usually been laid down before PDF::Table realizes that it's going to have to go to the next page. I'm assuming that you're trying to avoid having a short (less than one page) table being split across two pages. Either figure out how to then _remove_ the partial table from the `$pdf` structure (canceling the table call _before_ it's output to file), or figure out in advance how long the table will be (a "dummy" run), and then actually run it either at the current page location, or go to a new page.

**Comment by djzort** [comment]
so how to best communicate this to the code calling it?

**Comment by PhilterPaper** [comment]
Communicate what, the length of the table? At this time, there is no way to do it. In a future release I could look at a new flag (setting) that says to not actually _write_ anything to the file, but to just return the length. It might also return some information about the height of each row, so you could make a decision about adjusting the height to force a page break where you want it. I'll have to think about how to handle this for page 3, 4, etc., especially if any header is repeated. Maybe `next_h` could (optionally) be an _array_ of heights?

Would this be useful to you?

**Comment by PhilterPaper** [comment]
Release 1.000 no longer says anything when a table spills to a new page, so I will close this ticket. 

I have added the request for preventing a short table from splitting across two pages (when it could fit on one) to the list of things to do. It will probably be a flag to just return the overall length, header length, and length of each row, without writing anything to the PDF. Then you can decide if you want to force it to the top of the next page. `next_y` and `next_h` may allow arrays of positions and heights, for finer control over where the table is split across pages.

**Comment by djzort** [comment]
Sincere thanks @PhilterPaper
