### ISSUE TITLE
Support PDF::Builder as alternative to PDF::API2; pull preparation

### ISSUE THREAD

**Issue by westmj** [PhilterPaper/PDF-Table#51]
I am a novice git user, perler and PDF generator, wanting 
to give back to perl.

I am lately becoming more familiar with PDF::API2 and PDF::Table,
and curious about PDF::Builder.

As a personal project, I propose to try to make a pull request 
that will allow PDF::Table to be used in PDF::Builder.

I want to get some high-level advice, precautions, warnings, 
etc., so that I can avoid traps that may be obvious to others.

So.... comments, questions, suggestions, etc., appreciated...

- separate pull requests for code and pod?

- first, "silently" add PDF::Builder code support, tests?

- when tests good, allow pull, wait for any unexpected failures
  in PDF::API2 use.

- when pull accepted and aged, and privately tested in PDF::Builder,
  go "public" by changing pod to reflect PDF::API2 compatibility

While I have your attention, separately I am considering other
"issues" or code changes (pulls) or pod changes or addition
of "examples" (see https://github.com/kamenov/PDF-Table/pulls).  
Any recommendations of best practices?

Also...

Can images be placed into table cells? Or would it be necessary
to keep track of (x,y) coordinates, and place images in the 
appropriate location?  

Can anyone comment on the closest analogues of the algorithms
and capabilities of PDF::Table?  Are html tables a close relative?
Was there a predecessor or inspiration for PDF::Table? 

Please note: PDF::Table contains this pod:

    font - instance of PDF::API2::Resource::Font defining the fontf to be used
    in the table
        Value: can be any PDF::API2::Resource::* type of font Default: 'Times'
        with UTF8 encoding

            font => $pdf->corefont("Helvetica", -encoding => "utf8")

However, I think this may be misleading, as "Helvetica" apparently does not 
really support "utf8" as a naive user might expect.  I believe this should
generate a warning or worse. Maybe the code needs more, maybe the pod needs
changes.  Thoughts? Issues, pulls?

Thanks for your attention.

**Comment by PhilterPaper** [comment]
I am going to try to generate a PR for PDF::Builder support, unless someone else wants to go ahead and make the change already (per my note in another ticket). Speaking of that other ticket, I make a request there _not_ to split a word unless it's absolutely necessary, and to add a hyphen - at the split.

Regarding Helvetica and UTF-8, all corefonts are single byte encodings, as are Type1 (PS). In PDF::Builder I just pushed a change to forbid "utf*" encodings on all but TTF/OTF (ttfont) fonts. Presumably CJK fonts are UTF-8, although they seem to be odd creatures. Other multibyte encodings (particularly for East Asian alphabets) will be added to the corefont/psfont ban in the future.

**Comment by westmj** [comment]
You doing the PR seems good, I got confused about antecedents. Just a rookie.

**Comment by PhilterPaper** [comment]
Yesterday I sent a revised Table.pm to the author (something didn't go right with the setup to create a PR -- it keeps insisting that I'm trying to push to _his_ repository, not mine). Hopefully soon we'll see my changes to permit either PDF::API2 or PDF::Builder to be used without modification to PDF::Table. It doesn't look like PDF::Table _requires_ either product (forcing one on installation).

I changed corefont() calls in PDF::Table to use 'latin1' encoding rather than 'utf8', and fixed a few typos. 

I don't think there's any provision for images... have you tried placing one at the current cell position? If it doesn't work, hopefully it would be a small extension to permit that. Returning the current cell text position could be useful (you may be able to use API2/Builder's textpos() call), but you would still need a way to "reserve" sufficient space for an image (forcing sufficient row height and column width). I haven't played with PDF::Table all that much, but from glancing over the POD, it looks like there's a lot of HTML-like capability in there.

You might want to give the new package Text::Layout a try. It's a layer on top of API2 or Builder that permits easy font selection, with HTML-like b, i, s, u, tt, size change, etc. tags. I have no idea if it's compatible with PDF::Table, but it might be worth a look.

**Comment by PhilterPaper** [comment]
By the way, I did manage to set up a PR a few days ago.  No word from Desislav yet.

I'm still pondering what would be involved to support images in table cells.

**Comment by westmj** [comment]
I noticed that, thanks.

Mike West <mwjwest@gmail.com>

Phone & WhatsApp: +1-302-559-3642
Address: Casa Alquimía
350 m SUR y 80 m ESTE
    de la Gasolinera Monteverde
Monteverde, Puntarenas, Costa Rica  60109
www.facebook.com/mwjwest mwjwest.wordpress.com

**Comment by PhilterPaper** [comment]
A while back, Desislav said he was too busy to work on PDF::Table for now, but would give me "merge" authority so my PR (changes) could be brought in (merged). I haven't seen any indication yet that he ever did that. Then, there is still the issue of his issuing a new build on CPAN. As a shortcut, you can go to https://github.com/PhilterPaper/PDF-Table, which is my fork with my changes. It's not in a form installable with cpan or cpanm, but you should be able to just copy the files into the right place. You might even be able to do a `cpan` install right from the desktop directory copied from GitHub.

**Comment by PhilterPaper** [comment]
Regarding support of images, I think it's time to step back and take a hard long look at the architecture of Table. Rather than trying to recreate something like API2 or Builder's functionality, I think the preferable thing would be to somehow create a flexible space (variable width and height) that you just pour your content into using regular API2 or Builder calls. If those calls have been told that the cell is more-or-less the whole page they can work with, that might be the cleanest. This is getting into the whole issue of high-level page layout and paragraph shaping, which needs to be addressed either in PDF::Builder or a new layout module. Anyway, something to think about before adding more bits and pieces.

**Comment by PhilterPaper** [comment]
0.12 was released yesterday with full PDF::Builder support. Therefore I am closing this ticket. Perhaps later someone can open a ticket for image support.
