### ISSUE TITLE
Failed test 'POD test for blib/lib/PDF/Table.pm'

### ISSUE THREAD

**Issue by eserte** [PhilterPaper/PDF-Table#61]
On some of my smokers t/pod.t fails:
```
#   Failed test 'POD test for blib/lib/PDF/Table.pm'
#   at /usr/perl5.16.3t/lib/site_perl/5.16.3/Test/Pod.pm line 184.
# blib/lib/PDF/Table.pm (2144): Unknown directive: =head5
# blib/lib/PDF/Table.pm (2274): Unknown directive: =head5
# Looks like you failed 1 test of 1.
t/pod.t ........ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
```

**Comment by PhilterPaper** [comment]
This seems to be a common failure in the latest round (use of **=head5**). Perhaps it will go away if I up the minimum version of Test::Pod to 1.52 (which is over two years old)? Or I can restructure the POD _not_ to use `=head5`. Or I can just drop pod.t (and manifest.t), since they really don't prove anything. I generate the HTML from POD during the package build process, so it should always be clean, and any manifest problems should get caught then, too. Anyone with a strong preference?

**Comment by PhilterPaper** [comment]
I went ahead and adjusted the POD not to use `=head5` any more (even though it's legal), as it looked crummy anyway (font size _smaller_ than the body text!). I also bumped up the minimum Test::Pod to 1.52, which is current (and supports `=head5`).

I'm still wondering if I should drop t/pod.t and t/manifest.t, as I'm not really sure what their point is. Perhaps I should "hide" them behind `$ENV['AUTHOR_TESTING']`? As part of the build process, I generate HTML from the POD, so any problems should show up there. t/manifest.t is just annoying, as when I test run it for routine checking, it always complains about files that MANIFEST.SKIP says to skip when creating the install package. Does the Test::CheckManifest utility _not_ pay attention to MANIFEST.SKIP?

**Comment by eserte** [comment]
Many members of the perl testers community think that such tests should run only for the author (i.e. by using something like `$ENV{'AUTHOR_TESTING'}`, like you already suggested).

I don't know about Test::CheckManifest, but your description sounds like a bug to me.

**Comment by PhilterPaper** [comment]
I changed both pod.t and manifest.t to author-only, just to get them out of my hair. I'll issue a new build (release 1.001) as soon as I figure out what to do (if anything) about the long double problem (#60). Thanks for the information!
