### ISSUE TITLE
backward compatibility issue after upgrade to v1.00

### ISSUE THREAD

**Issue by davewood** [PhilterPaper/PDF-Table#62]
Update: correct title should  be: **table continues on next page if row/cell overflows**

my code creates a pdf with 4 tables.

the first 3 tables are small, only 1-5 rows each. after that a large table is appended.

if the content of last cell in the 3rd table is too large the table now continues on a new page, leaving the first page almost empty.

if i shorten the content of that cell it doesnt create a new page and works as expected.

### Page 1
![pdftable-v0 12-page001](https://user-images.githubusercontent.com/304895/98228660-29df9100-1f59-11eb-8b0f-2fa5affc5954.png)

Note: for some reason PDF::Table inserts a whitespace into the word "Industriefilmproduktion" and renders it as  "Industriefil mproduktion" both with version 0.12 and 1.00. could this be the force split due to `'max_word_length' => 50`?

### Page 1
![pdftable-v1 00-page001](https://user-images.githubusercontent.com/304895/98228657-2946fa80-1f59-11eb-88b8-f1452c83bb45.png)

### Page 2
![pdftable-v1 00-page002](https://user-images.githubusercontent.com/304895/98228652-2815cd80-1f59-11eb-92f1-4057b829a5a0.png)

**Comment by davewood** [comment]
i also get this error, so for some reason v1.00 thinks the table spills to the next page when in reality the content of a cell overflows.

```
!!! Error: !!! Table spills to next page, but no next_y was given! Using 757.728.
 at lib/MyAppModel/RenderPDF.pm line 134.
```

**Comment by PhilterPaper** [comment]
Have you checked the allowed height for the table (`h` or `start_h` for the first page of the table, `next_h` for spill pages)? It looks like it thinks that the allowed height is very short, forcing the table to end early. If you could show the code just for the offending table, starting at the correct `y` or `start_y`, that would help to diagnose the problem. 

It doesn't look like a cell overflow from here -- the cell appears to be the same width, with the text split in the same place. You may want to adjust `max_word_length` to a larger value than 12 so that word isn't split in the middle.

The following table appears to have a bar code that is spanning two rows. You may want to consider setting a taller row (`min_rh` or `row_height` for the small table or just the row (`row_props`) so that the rule does not cross the bar code.

**Comment by davewood** [comment]
increasing start_h fixed it.

**Comment by davewood** [comment]
i would think barcode and table do not interact.

```
      if ($obj->{is_order}) {
          my $bc = $pdf->xo_code128(
            -code => 'order: ' . $input->id,
            -zone => 15,
            -umzn => 0,
            -lmzn => 0,
            -font => $obj->{font_arial},
            -fnsz => 0,
          );
          my $gfx = $page->gfx();
          my $offset = 20; # dont know why 20 but it places the barcode at the correct height
          $gfx->formimage($bc, 425, $y-$offset);
      }
  
      my $data = [
          [$title,       ' '],
          [$input->name, ' '],
      ];
```

**Comment by PhilterPaper** [comment]
The barcode is in a cell, so it can't be an image. It must be output as text (a font). If the font_size used produces something (the bard code) much taller than normal text (Latin alphabet), it would vertically overflow the cell and intrude into the row above.

**Comment by davewood** [comment]
you are the expert here but still, are you sure? where in my code is the barcode inserted into a cell?

**Comment by PhilterPaper** [comment]
> This assumes that the barcode is something within the cell, and not completely separate at page level that just happens to overlay a cell.

Is this barcode something applied over the page, and just happens to land within a cell (or you intend it to appear within a cell, even though it's not laid down as part of the table)?

Otherwise, with `start_h` (or just `h`) fixed, is the problem resolved? With default padding increased a bit, it's possible that your original height was now a bit too small (either reduce padding explicitly, or increase the height). See the "compatibility" section in the POD/Table.html.

**Comment by davewood** [comment]
i think the problem was exactly what you described. its fixed as far as i am concerned

**Comment by PhilterPaper** [comment]
Keep in mind that "height" (start_y/y and next_y) is only the _maximum_ height of the table allowed, not the precise actual height to be used. You don't have to sweat the precise height, just give the maximum you want this table to occupy on the page.
