### ISSUE TITLE
Different text colors and fonts in a single cell

### ISSUE THREAD

**Issue by abeverley** [PhilterPaper/PDF-Table#74]
I have a requirement to insert different coloured text and different fonts within a single table cell. I have some ideas as to how to implement this, and I've looked at the code and can see that it's possible.

Before I create a PR, I'd be grateful for some feedback as to:

- Whether this feature would be merged in principle
- Any suggests for the API (I'm thinking something like ```PDF::TextBlock``` but would welcome thoughts)

Thanks,

Andy

**Comment by PhilterPaper** [comment]
At this time, the finest granularity for text colors and font selection is at the cell level. Are you thinking of writing some sort of HTML-style markup for the cell's text, to change colors and fonts? That's actually quite a bit of work to do it right. I also have in the queue some code from @stefanalt (#66) to allow unflowed text (e.g., `<code>`). I'm thinking that perhaps such capabilities should be put in PDF::Builder itself, but in a more general HTML sense, rather than cluttering up PDF::Table with such things.

**Comment by abeverley** [comment]
> Are you thinking of writing some sort of HTML-style markup for the cell's text, to change colors and fonts?

Yes, I was thinking something along those lines

> I'm thinking that perhaps such capabilities should be put in PDF::Builder itself, but in a more general HTML sense, rather than cluttering up PDF::Table with such things.

Yes, I agree, that thought did occur to me. Quite a big job I assume, but definitely best for the long-term. Is that something I might be able to sponsor you for?

**Comment by PhilterPaper** [comment]
I haven't given a lot of thought to sponsorship, mostly as this is basically a hobby side project. Things really slowed down this summer and fall as Life threw me a few curve balls (serious family and personal illnesses) and I was just unable to devote nearly as much time as I wanted to PDF::Builder and PDF::Table. If someone wants to throw me some $$ to hurry up work, that would be much appreciated help, but I'm not sure I can make any promises about delivery schedules. Are there standard ways of sponsorship acceptable to the community? (I have a PayPal account.)

For something of this magnitude, help with design and coding would be a great help. Not necessarily PRs, at least until it's focused on some specific new routines that I can hand off to someone. The design needs to be worked out up front, as I don't want someone to do a lot of coding and testing, only to have me reject it because it doesn't fit with where I want it to go. Besides tested code, t-tests, other tests, and at least an outline of documentation are requested. I'm sure that I'll end up editing everything to some extent (to fit my style, if nothing else), but having a start on it would be a relief. Don't forget to read the "Roadmap" files for both PDF::Builder and PDF::Table, to see where I want to go.

I suggest adding these capabilities to PDF::Builder rather than PDF::Table, as Builder needs generalized markup capabilities for formatting paragraphs, etc. anyway, and they would then come free to PDF::Table. Of course, you wouldn't get them if using PDF::API2, but Builder is expected to be essentially a superset of API2 function. Anyway, if interested, let's discuss.

**Comment by PhilterPaper** [comment]
Some further thoughts: people like to mark up text in all sorts of ways, and I'd like to (eventually) accommodate as many of them as I can. These include, but are not limited to:

- HTML `<i>italic text</i>`
- BBCode `[I]italic text[/I]`
- LaTeX `\ital{italic text}`
- Markdown `_italic text_`

It would be nice to allow one (or more) of these within a block of text. I don't know how big an issue it would be to mix and match within a paragraph, especially for "structural" block items such as lists. Probably they would be converted on-the-fly to, say, HTML, which would then be processed. HTML and LaTeX are well standardized, but others are something of a free-for-all (with BBCode being similar to HTML).

**Comment by abeverley** [comment]
> Are there standard ways of sponsorship acceptable to the community?

A couple of ways you might like to consider sponsorship are [GitHub sponsors](https://github.com/sponsors) and [Open Collective](https://opencollective.com/)

> Anyway, I plan to have this in PDF::Builder

Totally agree, makes sense

> For something of this magnitude, help with design and coding would be a great help

I've enlisted @domm to help with this task. I understand he's busy at the moment, but I've asked him to liaise and help you (if/as required) over the coming weeks/months.

> Further discussion should probably move over to PDF::Builder

Very happy with that. Shall I close this issue and open a new one there?

**Comment by PhilterPaper** [comment]
OK, I'll close this one. Please open a new one on PDF::Builder (Perl-PDF-Builder), referencing this ticket as well as to Road Maps on both products and anything else that would provide useful information to someone. I'll be adding my thoughts on the architecture/design. Thanks, and looking forward to moving this thing.

**Comment by PhilterPaper** [comment]
By the way, have you looked at Text::Layout? It may do what you want, to some degree. I have not tried it with PDF::Table, although it is supposed to lay out text of a certain column width at a given x,y. I don't think PDF::Table will be able to figure out a cell _height_ if the font or font size is changing, but it might be worth a look.

**Comment by PhilterPaper** [comment]
Today I took a long look at Text::Layout, and unfortunately it appears to be nowhere near Ready for Prime Time. Among other things, word-wrapping is not yet implemented, which is vital for turning a single string paragraph into a multi-line paragraph of
fixed width (cell width minus some margins). The author said this is all done, but the code just has dummy stubs. That's too bad, because the font selection, color, size, style, etc. all seem to be working.
